trigger:
- main   # runs on every push to main branch

pool:
  vmImage: 'ubuntu-latest'

steps:
# Step 1: Use Python
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

# Step 2: Install dependencies
- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

# Step 3: Run your main RAG app
- script: |
    python SOK_XGBoost_Gradnt_Boost_Breast_Cancer.py
  displayName: 'Run RAG Application'
